services:
  - type: web
    name: reflectly-server
    runtime: node
    rootDir: server
    plan: standard
    buildCommand: npm install --legacy-peer-deps
    startCommand: node video-converter-api.js
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: rilio-website
    runtime: static
    rootDir: web
    staticPublishPath: .
    buildCommand: ""
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
